#-------------------------------------------------------------
# Manifest File to create Deployment with Labels and ReplicaSet
#
# Copyleft (c) by Alex Rez 2022
#-------------------------------------------------------------
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-replicas
  labels:
    app  : my-k8s-application
    env  : prod
    owner: AlexRez
spec:
  replicas: 3
  selector:
    matchLabels:
      project: bbb
  template:
    metadata:
      labels:
        project: bbb
    spec:
      containers:
        - name : bbb-web
          image: adv4000/k8sphp:version1
          ports:
            - containerPort: 80