#-------------------------------------------------------------
# Manifest File to create Simple Deployment with Labels
#
# Copyleft (c) by Alex Rez 2022
#-------------------------------------------------------------
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app : my-k8s-application
spec:
  selector:
    matchLabels:
      project: aaa
  template:
    metadata:
      labels:
        project: aaa
    spec:
      containers:
        - name : aaa-web
          image: adv4000/k8sphp:latest
          ports:
            - containerPort: 80